-- Database export: zariya_loan
-- Date: 2026-07-16 17:13:13
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `loan_voucher` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `voucher_no` varchar(64) NOT NULL COMMENT '借据号',
  `apply_no` varchar(64) NOT NULL COMMENT '申请单号',
  `disbursement_no` varchar(64) NOT NULL COMMENT '放款单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '贷款产品ID',
  `borrow_count` int(11) NOT NULL DEFAULT '0' COMMENT '借款次数, 0,1,2,3,4,5,6...',
  `loan_amount` decimal(18,2) NOT NULL COMMENT '借款金额',
  `term` int(11) NOT NULL COMMENT '分期期数，例如 2、4、6',
  `period_days` int(11) NOT NULL COMMENT '每期天数，例如 15 天',
  `total_days` int(11) NOT NULL COMMENT '总借款天数，installment_count * period_days',
  `daily_interest_rate` decimal(18,6) NOT NULL COMMENT '日利率，例如 0.0075',
  `overdue_rate` decimal(18,6) NOT NULL COMMENT '逾期费率，例如 0.023',
  `total_interest` decimal(18,2) NOT NULL COMMENT '总利息，借款时预计算',
  `total_service_fee` decimal(18,2) NOT NULL COMMENT '总服务费，借款时预计算',
  `total_payable_amount` decimal(18,2) NOT NULL COMMENT '理论应还金额，本金 + 利息 + 服务费',
  `waiver_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '抹零优惠金额，因向下取整产生的小数减免',
  `display_payable_amount` decimal(18,2) NOT NULL COMMENT '展示应还金额，用户端展示和实际收取金额',
  `start_date` date NOT NULL COMMENT '账单开始日期，第一期账单开始时间',
  `end_date` date NOT NULL COMMENT '账单结束日期 - 最后一期账单结束时间',
  `cooling_off_start_time` datetime DEFAULT NULL COMMENT '冷静期开始时间（放款成功时间）',
  `cooling_off_end_time` datetime DEFAULT NULL COMMENT '冷静期结束时间（放款成功时间 + 24 小时）',
  `fee_cap_amount` decimal(18,2) DEFAULT NULL COMMENT '费用上限金额（等于本金）',
  `state` int(11) NOT NULL COMMENT '借据状态',
  `accumulated_fee_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '累计费用金额，汇总已还和应还：利息+服务费+逾期费累计',
  `total_overdue_fee` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '总逾期费，汇总所有账单逾期费',
  `repay_coupon_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '还款优惠券金额，汇总子账单还款优惠金额',
  `paid_principal` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已还本金，汇总所有账单已还本金',
  `paid_interest` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已还利息，汇总所有账单已还利息',
  `paid_service_fee` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已还服务费，汇总所有账单已还服务费',
  `paid_overdue_fee` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已还逾期费，汇总所有账单已还逾期费',
  `paid_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '已还金额，汇总所有账单已还总金额',
  `remaining_principal` decimal(18,2) NOT NULL COMMENT '剩余应还本金',
  `remaining_interest` decimal(18,2) NOT NULL COMMENT '剩余应还利息',
  `remaining_service_fee` decimal(18,2) NOT NULL COMMENT '剩余应还服务费',
  `remaining_overdue_fee` decimal(18,2) NOT NULL COMMENT '剩余应还逾期费',
  `remaining_amount` decimal(18,2) NOT NULL COMMENT '剩余应还金额',
  `payment_account_id` bigint(20) DEFAULT NULL COMMENT '收款账户id',
  `fee_capped` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否达到费用上限，0否，1是',
  `fee_capped_time` datetime DEFAULT NULL COMMENT '达到费用上限时间，达到封顶时间',
  `settled_type` varchar(32) NOT NULL DEFAULT 'NONE' COMMENT '结清类型，NONE：未结清，NORMAL：正常结清，COOLING_OFF：冷静期结清，EARLY：提前结清',
  `settled_time` datetime DEFAULT NULL COMMENT '结清时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_voucher_no` (`voucher_no`) USING BTREE,
  UNIQUE KEY `idx_voucher_apply_no` (`apply_no`) USING BTREE,
  KEY `idx_voucher_user_id` (`user_id`) USING BTREE,
  KEY `idx_voucher_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='借据主表';;

CREATE TABLE `loan_coupon_log` (
  `id` bigint(20) NOT NULL COMMENT '主键ID - 自增ID',
  `coupon_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券编号',
  `template_id` bigint(20) NOT NULL COMMENT '优惠券模板id',
  `coupon_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券类型',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `biz_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联业务订单',
  `used_amount` decimal(18,2) DEFAULT NULL COMMENT '实际使用金额',
  `deduct_fee_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '抵扣费用类型 - Principal',
  `state` int(11) NOT NULL COMMENT '状态 - Locked/Used/Returned/Expired/Invalid',
  `used_time` datetime DEFAULT NULL COMMENT '使用时间',
  `back_time` datetime DEFAULT NULL COMMENT '退回时间',
  `back_reason_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退回原因类型',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '删除标识 - 0:未删除 1:已删除',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_coupon_log_coupon_no` (`coupon_no`) USING BTREE,
  KEY `idx_coupon_log_template_id` (`template_id`) USING BTREE,
  KEY `idx_coupon_log_user_id` (`user_id`) USING BTREE,
  KEY `idx_coupon_log_biz_no` (`biz_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠券使用记录表';;

CREATE TABLE `loan_payment_institution` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `institution_code` varchar(64) NOT NULL COMMENT '机构编码',
  `institution_name` varchar(128) NOT NULL COMMENT '机构名称',
  `display_name` varchar(128) NOT NULL COMMENT '前端展示名称',
  `institution_type` varchar(32) NOT NULL COMMENT '机构类型',
  `related_institution_code` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '关联机构编码',
  `ibft_imd` varchar(64) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否启用',
  `selectable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可选',
  `logo` varchar(256) DEFAULT NULL COMMENT 'logo',
  `sort` int(11) NOT NULL DEFAULT '0' COMMENT '排序，越大优先级越高',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '最近修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='支付机构';;

CREATE TABLE `loan_payment_account` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `user_id` bigint(20) NOT NULL COMMENT '用户id',
  `institution_code` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '机构编码',
  `identifier_enc` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '账号(加密)',
  `identifier_unique` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '账号(唯一key)',
  `state` int(11) NOT NULL COMMENT '状态',
  `is_snapshot` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否历史快照',
  `verification_time` datetime DEFAULT NULL COMMENT '最近一次验证时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '最近修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_payment_account_user_id` (`user_id`,`identifier_unique`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='支付账号';;

CREATE TABLE `loan_apply_record` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `apply_no` varchar(64) NOT NULL COMMENT '申请单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '贷款产品ID',
  `loan_amount` decimal(18,2) NOT NULL COMMENT '借款金额 - 客户申请的本金',
  `increase_limit_coupon_no` varchar(32) NOT NULL DEFAULT '0.00' COMMENT '提额券编号',
  `increase_limit_coupon_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '提额券金额',
  `term` int(11) NOT NULL COMMENT '分期期数，例如 2、4、6',
  `period_days` int(11) NOT NULL COMMENT '每期天数，例如 15 天',
  `total_days` int(11) NOT NULL COMMENT '总借款天数，installment_count * period_days',
  `daily_interest_rate` decimal(18,6) NOT NULL COMMENT '日利率， 例如 0.0075',
  `overdue_rate` decimal(18,6) NOT NULL COMMENT '逾期费率，例如 0.023',
  `total_interest` decimal(18,2) NOT NULL COMMENT '总利息，借款时预计算',
  `total_service_fee` decimal(18,2) NOT NULL COMMENT '总服务费，借款时预计算',
  `total_repay_amount` decimal(18,2) NOT NULL COMMENT '理论应还金额，本金 + 利息 + 服务费',
  `rounding_waiver_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '抹零优惠金额，因向下取整产生的小数减免',
  `display_total_payable_amount` decimal(18,2) NOT NULL COMMENT '展示应还金额，用户端展示和实际收取金额',
  `start_date` date NOT NULL COMMENT '账单开始日期，第一期账单开始时间',
  `end_date` date NOT NULL COMMENT '账单结束日期',
  `quick_review` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否快速通过，是否授信审核通过 15 分钟内借款',
  `state` int(11) NOT NULL COMMENT '状态',
  `pre_state` int(11) DEFAULT NULL COMMENT '验证状态',
  `risk_state` int(11) DEFAULT NULL COMMENT '风控状态',
  `term_infos` json DEFAULT NULL COMMENT '分期明细',
  `reject_reason` varchar(255) DEFAULT NULL COMMENT '拒绝原因 - 审批拒绝原因',
  `review_time` datetime DEFAULT NULL COMMENT '审批时间',
  `payment_account_id` bigint(20) DEFAULT NULL COMMENT '收款账户id',
  `disbursement_state` int(11) DEFAULT NULL COMMENT '放款状态， Pending/Success/Failed/null',
  `disbursement_time` datetime DEFAULT NULL COMMENT '放款时间 - 实际放款时间',
  `disbursement_no` varchar(64) DEFAULT NULL COMMENT '放款单号',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_apply_record_apply_no` (`apply_no`) USING BTREE,
  KEY `idx_apply_record_user_id` (`user_id`) USING BTREE,
  KEY `idx_apply_record_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='借款申请';;

CREATE TABLE `loan_early_settlement_record` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `settlement_no` varchar(64) NOT NULL COMMENT '结清单号',
  `voucher_no` varchar(64) NOT NULL COMMENT '借款订单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID',
  `settlement_date` date NOT NULL COMMENT '客户发起结清日期',
  `original_remaining_contract_principal` decimal(18,2) DEFAULT NULL COMMENT '原剩余本金',
  `original_remaining_overdue_fee` decimal(18,2) DEFAULT NULL COMMENT '原剩余逾期费',
  `paid_normal_principal_amount` decimal(18,2) DEFAULT NULL COMMENT '已经正常还款本金',
  `paid_normal_fee_interest` decimal(18,2) DEFAULT NULL COMMENT '已收正常收费利息',
  `paid_normal_fee_service_fee` decimal(18,2) DEFAULT NULL COMMENT '已收正常收费服务费',
  `actual_used_days` int(11) DEFAULT NULL COMMENT '实际占用天数 - 放款成功日至结清日前一天',
  `actual_payable_interest` decimal(18,2) DEFAULT NULL COMMENT '实际应收利息，按实际使用天数计算',
  `actual_payable_service_fee` decimal(18,2) DEFAULT NULL COMMENT '实际应收服务费，按实际使用天数计算',
  `settlement_payable_fee_amount` decimal(18,2) DEFAULT NULL COMMENT '提前结清应收总费用，原本金-已正常还款本金+（实际应收利息+实际应收服务费）-已收正常收费利息-已手正常收费服务费+原剩余逾期费',
  `waived_interest` decimal(18,2) DEFAULT NULL COMMENT '减免利息',
  `waived_service_fee` decimal(18,2) DEFAULT NULL COMMENT '减免服务费',
  `waived_overdue_fee` decimal(18,2) DEFAULT NULL COMMENT '减免逾期费',
  `settlement_amount` decimal(18,2) DEFAULT NULL COMMENT '最终结清金额 - 客户需要支付金额；提前结清应收总费用-减免利息-减免服务费-减免逾期费',
  `repayment_no` varchar(255) DEFAULT NULL COMMENT '还款订单号 - 关联还款订单',
  `status` varchar(255) DEFAULT NULL COMMENT '结清状态 - Pending/Paid/Cancelled/Expired',
  `paid_time` datetime DEFAULT NULL COMMENT '支付时间 - 结清支付成功时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_early_settlement_no` (`settlement_no`) USING BTREE,
  KEY `idx_early_settlement_voucher_no` (`voucher_no`) USING BTREE,
  KEY `idx_early_settlement_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='提前结清记录表';;

CREATE TABLE `loan_repayment_allocation` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `repayment_no` varchar(64) DEFAULT NULL COMMENT '还款订单号',
  `voucher_no` varchar(64) DEFAULT NULL COMMENT '借据好',
  `bill_no` varchar(64) DEFAULT NULL COMMENT '账单号 - 关联 loan_bill',
  `user_id` bigint(20) DEFAULT NULL COMMENT '客户ID',
  `product_id` bigint(20) DEFAULT NULL COMMENT '产品ID',
  `term_seq` int(11) DEFAULT NULL COMMENT '期数',
  `fee_type` varchar(255) DEFAULT NULL COMMENT '费用类型 - Principal/Interest/ServiceFee/OverdueFee',
  `allocated_amount` decimal(18,2) DEFAULT NULL COMMENT '分配金额 - 本次还款分配金额',
  `allocation_order` int(11) DEFAULT NULL COMMENT '分配顺序 - 冲抵顺序',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_epayment_allocation_repayment_no` (`repayment_no`) USING BTREE,
  KEY `idx_epayment_allocation_voucher_no` (`voucher_no`) USING BTREE,
  KEY `idx_epayment_allocation_bill_no` (`bill_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='还款分配明细表';;

CREATE TABLE `loan_fee_adjust` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `adjust_no` varchar(64) NOT NULL COMMENT '调整单号',
  `voucher_no` varchar(64) NOT NULL COMMENT '借款订单号',
  `bill_no` varchar(64) NOT NULL COMMENT '账单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID',
  `fee_type` varchar(32) NOT NULL COMMENT '费用类型 - Interest/ServiceFee/OverdueFee',
  `adjust_type` varchar(255) DEFAULT NULL COMMENT '调整类型 - Increase/Decrease/Waive',
  `state` int(11) NOT NULL COMMENT '状态 - Pending/Approved/Rejected',
  `adjust_amount` decimal(18,2) DEFAULT NULL COMMENT '调整金额',
  `before_amount` decimal(18,2) DEFAULT NULL COMMENT '调整前金额',
  `after_amount` decimal(18,2) DEFAULT NULL COMMENT '调整后金额',
  `reason` varchar(255) DEFAULT NULL COMMENT '调整原因',
  `operator_id` bigint(20) DEFAULT NULL COMMENT '操作人ID',
  `reviewer_id` bigint(20) DEFAULT NULL COMMENT '审核人ID',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间 - 审核时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_fee_adjust_no` (`adjust_no`) USING BTREE,
  KEY `idx_fee_adjust_voucher_no` (`voucher_no`) USING BTREE,
  KEY `idx_fee_adjust_bill_no` (`bill_no`) USING BTREE,
  KEY `idx_fee_adjust_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='费用调整表';;

CREATE TABLE `loan_overdue_record` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `overdue_no` varchar(64) NOT NULL COMMENT '逾期记录号',
  `voucher_no` varchar(64) NOT NULL COMMENT '借款订单号',
  `bill_no` varchar(64) NOT NULL COMMENT '账单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID',
  `term_seq` int(11) DEFAULT NULL COMMENT '期数',
  `overdue_date` date DEFAULT NULL COMMENT '逾期日期 - 产生逾期费的日期',
  `overdue_days` int(11) DEFAULT NULL COMMENT '逾期天数 - 第几天逾期',
  `overdue_rate` decimal(18,2) DEFAULT NULL COMMENT '逾期费率 - 例如 0.023',
  `overdue_principal` decimal(18,2) DEFAULT NULL COMMENT '逾期本金 - 逾期未还本金',
  `overdue_base_amount` decimal(18,2) DEFAULT NULL COMMENT '逾期计算基数 - 计算逾期费的金额，部分还款后基数会发生变化',
  `overdue_fee_amount` decimal(18,2) DEFAULT NULL COMMENT '当日逾期费 - 当天产生的逾期费',
  `original_overdue_fee` decimal(18,2) DEFAULT NULL COMMENT '封顶前应收逾期费 - 按公式计算的原始逾期费',
  `posted_overdue_fee` decimal(18,2) DEFAULT NULL COMMENT '封顶后实际入账逾期费 - 受 100% 费用上限限制后的实际入账金额',
  `posted_time` datetime DEFAULT NULL COMMENT '入账时间 - 写入账单时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_overdue_no` (`overdue_no`) USING BTREE,
  UNIQUE KEY `idx_overdue_voucher_no` (`voucher_no`) USING BTREE,
  UNIQUE KEY `idx_overdue_bill_no` (`bill_no`) USING BTREE,
  UNIQUE KEY `idx_overdue_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='逾期费用记录表';;

CREATE TABLE `loan_product_term_rule` (
  `id` bigint(20) NOT NULL COMMENT '主键ID - 自增ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品id',
  `min_loan_amount` decimal(18,2) NOT NULL COMMENT '最小借款金额 - 例如 2000',
  `max_loan_amount` decimal(18,2) NOT NULL COMMENT '最大借款金额 - 例如 8000',
  `available_terms` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '可选期数 - 例如 2 或 2,3',
  `default_term` int(11) DEFAULT NULL COMMENT '默认期数 - 默认选中的期数',
  `enabled` tinyint(4) DEFAULT NULL COMMENT '是否启用 - 0否，1是',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '删除标识 - 0:未删除 1:已删除',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_product_term_rule_product_id` (`product_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='借款产品期数规则表';;

CREATE TABLE `loan_repayment_order` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `repayment_no` varchar(64) NOT NULL COMMENT '还款订单号',
  `voucher_no` varchar(64) NOT NULL COMMENT '借款订单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID',
  `channel_pay_no` varchar(64) DEFAULT NULL COMMENT '渠道支付号',
  `payable_amount` decimal(18,2) DEFAULT NULL COMMENT '应还总金额',
  `difference_amount` decimal(18,2) DEFAULT NULL COMMENT '差额金额',
  `coupon_no` varchar(32) DEFAULT NULL COMMENT '使用的优惠券编号',
  `coupon_amount` decimal(18,2) DEFAULT NULL COMMENT '优惠券抵扣金额',
  `repay_start_time` datetime DEFAULT NULL COMMENT '还款发起时间',
  `repay_success_time` datetime DEFAULT NULL COMMENT '还款成功时间',
  `repay_type` varchar(32) DEFAULT NULL COMMENT '还款类型',
  `repay_amount` decimal(18,2) DEFAULT NULL COMMENT '还款金额, 客户实际支付金额',
  `pay_channel` varchar(32) DEFAULT NULL COMMENT '支付渠道, Easypaisa/JazzCash/Bank/Manual',
  `pay_txn_no` varchar(128) DEFAULT NULL COMMENT '支付流水号, 三方支付流水号',
  `wallet_type` varchar(32) DEFAULT NULL COMMENT '付款钱包类型, Easypaisa/JazzCash/Bank',
  `wallet_real_name` varchar(64) DEFAULT NULL COMMENT '付款人姓名',
  `wallet_account` varchar(64) DEFAULT NULL COMMENT '付款账户号',
  `pay_state` int(11) DEFAULT NULL COMMENT '支付状态',
  `match_state` int(11) DEFAULT NULL COMMENT '匹配状态',
  `reconcile_state` int(11) DEFAULT NULL COMMENT '对账状态',
  `fail_reason` varchar(255) DEFAULT NULL COMMENT '支付失败原因',
  `reconciled_time` datetime DEFAULT NULL COMMENT '对账完成时间',
  `expire_time` datetime DEFAULT NULL COMMENT '到期时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_repayment_order_no` (`repayment_no`) USING BTREE,
  KEY `idx_repayment_order_voucher_no` (`voucher_no`) USING BTREE,
  KEY `idx_repayment_order_channel_pay_no` (`channel_pay_no`) USING BTREE,
  KEY `idx_repayment_order_user_id` (`user_id`,`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='还款订单表';;

CREATE TABLE `loan_voucher_bill` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `bill_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '账单号，普通分期账单号',
  `voucher_no` varchar(64) NOT NULL COMMENT '借款订单号，关联借款订单',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID - 产品ID',
  `term_seq` int(11) DEFAULT NULL COMMENT '期数 - 第 1/2/3 期',
  `term` int(11) DEFAULT NULL COMMENT '总期数 - 总分期期数',
  `start_date` date DEFAULT NULL COMMENT '账单开始日 - 本期计息开始日',
  `end_date` date DEFAULT NULL COMMENT '账单到期日',
  `repay_date` date DEFAULT NULL COMMENT '本期还款日',
  `period_days` int(11) DEFAULT NULL COMMENT '账单天数 - 例如 15 天',
  `state` int(11) DEFAULT NULL COMMENT '账单状态',
  `payable_principal` decimal(18,2) DEFAULT NULL COMMENT '应还本金，本期应还本金',
  `payable_interest_amount` decimal(18,2) DEFAULT NULL COMMENT '应还利息',
  `payable_service_fee` decimal(18,2) DEFAULT NULL COMMENT '应还服务费',
  `payable_overdue_fee` decimal(18,2) DEFAULT NULL COMMENT '应还逾期费',
  `payable_amount` decimal(18,2) DEFAULT NULL COMMENT '当前应还金额，优惠后本期应还本金+应还利息+应还服务费+应还逾期费',
  `paid_principal` decimal(18,2) DEFAULT NULL COMMENT '已还本金 - 本期已还本金',
  `paid_interest` decimal(18,2) DEFAULT NULL COMMENT '已还利息 - 本期已还利息',
  `paid_service_fee` decimal(18,2) DEFAULT NULL COMMENT '已还服务费',
  `paid_overdue_fee` decimal(18,2) DEFAULT NULL COMMENT '已还逾期费',
  `paid_amount` decimal(18,2) DEFAULT NULL COMMENT '本期已还总金额',
  `remaining_principal` decimal(18,2) DEFAULT NULL COMMENT '剩余本金 - 本期剩余本金',
  `remaining_interest` decimal(18,2) DEFAULT NULL COMMENT '剩余利息 - 本期剩余利息',
  `remaining_service_fee` decimal(18,2) DEFAULT NULL COMMENT '剩余服务费 - 本期剩余服务费',
  `remaining_overdue_fee` decimal(18,2) DEFAULT NULL COMMENT '剩余逾期费 - 本期剩余逾期费',
  `remaining_amount` decimal(18,2) DEFAULT NULL COMMENT '剩余应还金额 - 本期剩余应还',
  `overdue_days` int(11) NOT NULL DEFAULT '0' COMMENT '逾期天数 - 当前逾期天数',
  `is_overdue` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否逾期 - 0否，1是',
  `settled_type` varchar(32) NOT NULL DEFAULT 'NONE' COMMENT '结清类型，NONE：未结清，NORMAL：正常结清，COOLING_OFF：冷静期结清，EARLY：提前结清，CURRENT_EARLY',
  `settled_time` datetime DEFAULT NULL COMMENT '结清时间 - 普通账单被关闭时间',
  `settlement_record_no` varchar(255) DEFAULT NULL COMMENT '提前结清记录号',
  `settlement_bill_no` varchar(255) DEFAULT NULL COMMENT '结清账单号 - 普通账单被提前结清关闭时，关联这笔提前结清账单',
  `batching_time` datetime DEFAULT NULL COMMENT '最后一次跑批时间 - 跑批时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_voucher_bill_no` (`bill_no`) USING BTREE,
  KEY `idx_voucher_bill_voucher_no` (`voucher_no`) USING BTREE,
  KEY `idx_voucher_bill_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='还款计划表';;

CREATE TABLE `loan_coupon_template` (
  `id` bigint(20) NOT NULL COMMENT '主键ID - 自增ID',
  `coupon_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券名称',
  `coupon_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券类型',
  `coupon_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '优惠券金额',
  `product_id` bigint(20) DEFAULT NULL COMMENT '适用产品ID',
  `effect_time` datetime DEFAULT NULL COMMENT '生效开始时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `issued_count` int(11) NOT NULL DEFAULT '0' COMMENT '已发放数量',
  `rule_config` json DEFAULT NULL COMMENT '券规则',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '删除标识 - 0:未删除 1:已删除',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠券模板';;

CREATE TABLE `loan_credit_quota` (
  `id` bigint(20) NOT NULL COMMENT 'id,对应授信记录id',
  `user_id` bigint(20) NOT NULL COMMENT '用户id',
  `total_credit` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '总授信额',
  `used_credit` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '已用额度（已借出尚未还清）',
  `locked_credit` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '冻结额度（放款中等被冻结）',
  `approved_time` datetime DEFAULT NULL COMMENT '授信通过时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除，0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '最近修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_credit_apply_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='授信额度';;

CREATE TABLE `loan_bill_fee_changelog` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `voucher_no` varchar(64) NOT NULL COMMENT '借款订单号',
  `bill_no` varchar(64) NOT NULL COMMENT '账单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID - 贷款产品ID',
  `term_seq` int(11) DEFAULT NULL COMMENT '当前期数',
  `fee_type` varchar(32) DEFAULT NULL COMMENT '费用类型 - Principal/Interest/ServiceFee/OverdueFee/coupon',
  `change_type` varchar(32) DEFAULT NULL COMMENT '变更类型 - Create/Increase/Decrease/Waive/Pay/Refund/Reverse',
  `source_type` varchar(32) DEFAULT NULL COMMENT '触发来源 - System/Repayment/Coupon/Manual/Overdue/EarlySettlement/Reconciliation',
  `source_no` varchar(64) DEFAULT NULL COMMENT '来源单号 - 还款单号、优惠券使用记录号、调整单号、提前结清单号等',
  `change_amount` decimal(18,2) DEFAULT NULL COMMENT '变更金额',
  `before_payable_amount` decimal(18,2) DEFAULT NULL COMMENT '变更前应收金额',
  `after_payable_amount` decimal(18,2) DEFAULT NULL COMMENT '变更后应收金额',
  `before_paid_amount` decimal(18,2) DEFAULT NULL COMMENT '变更前已收金额',
  `paid_change_amount` decimal(18,2) DEFAULT NULL COMMENT '本次入账金额',
  `after_paid_amount` decimal(18,2) DEFAULT NULL COMMENT '变更后已收金额 - 变更后已收金额',
  `before_remaining_amount` decimal(18,2) DEFAULT NULL COMMENT '变更前剩余金额',
  `after_remaining_amount` decimal(18,2) DEFAULT NULL COMMENT '变更后剩余金额',
  `waived_change_amount` decimal(18,2) DEFAULT NULL COMMENT '减免金额 - 本次减免金额',
  `change_reason` varchar(255) DEFAULT NULL COMMENT '变更原因 - 变更原因',
  `operator_id` bigint(20) DEFAULT NULL COMMENT '操作人ID - 系统操作可为空或填系统用户',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注 - 备注',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_bill_fee_changelog_voucher_no` (`voucher_no`) USING BTREE,
  KEY `idx_bill_fee_changelog_bill_no` (`bill_no`) USING BTREE,
  KEY `idx_bill_fee_changelog_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账单费用变更记录表';;

CREATE TABLE `loan_product` (
  `id` bigint(20) NOT NULL COMMENT '产品ID - 系统主键',
  `product_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品名称 - 后台展示名称',
  `state` int(11) NOT NULL COMMENT '状态',
  `currency` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '币种 - 借款币种',
  `min_loan_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '最低借款金额',
  `max_loan_amount` decimal(18,2) DEFAULT NULL COMMENT '最高借款金额',
  `amount_step` decimal(18,2) DEFAULT NULL COMMENT '金额步长, 借款金额递增单位',
  `min_term` int(11) NOT NULL COMMENT '最小分期期数, 最少可选期数',
  `max_term` int(11) DEFAULT NULL COMMENT '最大分期期数，最多可选期数',
  `default_term` int(11) DEFAULT NULL COMMENT '默认分期期数，用户默认看到的期数',
  `period_days` int(11) NOT NULL COMMENT '每期天数',
  `max_days` int(11) DEFAULT NULL COMMENT '借款最大总天数',
  `daily_interest_rate` decimal(10,6) NOT NULL COMMENT '日利率，每日利息费率',
  `daily_service_fee_rate` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '日服务费率',
  `overdue_rate` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '日逾期费率',
  `cooling_off_hours` int(11) NOT NULL DEFAULT '0' COMMENT '冷静期小时数',
  `cooling_off_fee_free` tinyint(1) DEFAULT NULL COMMENT '冷静期免息费，冷静期内是否免利息和服务费',
  `enable_early_repay` tinyint(1) DEFAULT NULL COMMENT '支持当期提前还款，是否允许未到期账单提前还款',
  `early_repay_open_days` int(11) DEFAULT NULL COMMENT '提前还款开放天数，到期日前几天开放入口',
  `enable_early_settlement` tinyint(1) DEFAULT NULL COMMENT '支持提前结清，是否允许一次性结清所有未还账单',
  `enable_partial_repay` tinyint(1) DEFAULT NULL COMMENT '支持部分还款，是否允许有多少钱还多少钱',
  `min_partial_repay_amount` decimal(18,2) DEFAULT NULL COMMENT '最低部分还款金额，单次部分还款最低金额',
  `max_overdue_days` int(11) DEFAULT NULL COMMENT '最大逾期天数，期费最多计算多少天',
  `max_overdue_fee_cap_rate` decimal(18,6) DEFAULT NULL COMMENT '逾期费封顶比例，逾期费相对本金的封顶比例',
  `repay_allocation_rule` json DEFAULT NULL COMMENT '还款冲抵规则，部分还款时先冲什么',
  `rounding_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '取整规则类型，金额展示和收取取整方式',
  `user_tag` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '适用用户类型，产品适合哪些用户',
  `risk_level` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '风险等级，产品适用风险等级',
  `sort_no` int(11) NOT NULL DEFAULT '0' COMMENT '排序号，前端展示排序',
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '删除标识 - 0:未删除 1:已删除',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间 - 记录创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间 - 记录更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='借贷产品表';;

CREATE TABLE `loan_repayment_bill` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `voucher_no` varchar(64) NOT NULL COMMENT '借款订单号',
  `bill_no` varchar(64) NOT NULL COMMENT '分期账单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `term_seq` int(11) DEFAULT NULL COMMENT '期数',
  `state` int(11) DEFAULT NULL COMMENT '状态',
  `original_bill_amount` decimal(18,2) DEFAULT NULL COMMENT '本期初始应还金额 - 生成还款订单时，该账单应还金额',
  `bill_remaining_amount` decimal(18,2) DEFAULT NULL COMMENT '账单剩余金额快照 - 生成还款订单时，该账单剩余待还',
  `coupon_amount` decimal(18,2) DEFAULT NULL COMMENT '本次还款优惠券分摊到这个账单的金额',
  `payable_amount` decimal(18,2) DEFAULT NULL COMMENT '本次应付金额, bill_remaining_amount - coupon_amount',
  `allocated_amount` decimal(18,2) DEFAULT NULL COMMENT '实际分配金额, 支付成功后实际分配到这个账单的金额',
  `difference_amount` decimal(18,2) DEFAULT NULL COMMENT '差额金额, payable_amount - allocated_amount',
  `paid_time` datetime DEFAULT NULL COMMENT '支付成功时间, 这个账单在本还款订单中完成的时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_repayment_bill_voucher_no` (`voucher_no`) USING BTREE,
  KEY `idx_repayment_bill_voucher_bill_no` (`bill_no`) USING BTREE,
  KEY `idx_repayment_bill_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='还款订单明细';;

CREATE TABLE `loan_disbursement_record` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `disbursement_no` varchar(64) DEFAULT NULL COMMENT '放款单号',
  `apply_no` varchar(64) NOT NULL COMMENT '申请单号',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID - 产品ID',
  `apply_amount` decimal(18,2) DEFAULT NULL COMMENT 'applyAmount',
  `disbursed_amount` decimal(18,2) DEFAULT NULL COMMENT '实际放款金额',
  `disbursement_channel` varchar(32) DEFAULT NULL COMMENT '放款渠道 - Easypaisa/JazzCash/Bank/Manual',
  `payment_account_id` bigint(20) DEFAULT NULL COMMENT '收款账户id',
  `channel_txn_no` varchar(128) DEFAULT NULL COMMENT '渠道交易号，三方放款流水',
  `state` int(11) NOT NULL COMMENT '放款状态 - Pending/Success/Failed/Cancelled',
  `fail_reason` varchar(255) DEFAULT NULL COMMENT '失败原因 - 放款失败原因',
  `request_time` datetime DEFAULT NULL COMMENT '发起时间，放款发起时间',
  `success_time` datetime DEFAULT NULL COMMENT '成功时间，放款成功时间',
  `callback_time` datetime DEFAULT NULL COMMENT '回调时间，渠道回调时间',
  `raw_payload` text COMMENT '原始报文 - 渠道原始返回',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除, 0:否，其他：删除时间戳',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_disbursement_record_no` (`disbursement_no`) USING BTREE,
  KEY `idx_disbursement_apply_no` (`apply_no`) USING BTREE,
  KEY `idx_disbursement_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='放款记录表';;

CREATE TABLE `loan_coupon_instance` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `coupon_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券编号',
  `template_id` bigint(20) NOT NULL COMMENT '优惠券模板id',
  `coupon_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券名称',
  `coupon_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券类型',
  `user_id` bigint(20) NOT NULL COMMENT '客户ID',
  `coupon_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '优惠券金额',
  `product_id` bigint(20) DEFAULT NULL COMMENT '适用产品ID',
  `state` int(11) NOT NULL COMMENT '状态',
  `effect_time` datetime NOT NULL COMMENT '生效开始时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `biz_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '锁定业务单号',
  `locked_time` datetime DEFAULT NULL COMMENT '锁定时间',
  `used_time` datetime DEFAULT NULL COMMENT '使用时间',
  `is_del` bigint(20) NOT NULL DEFAULT '0' COMMENT '删除标识 - 0:未删除 1:已删除',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_coupon_instance_coupon_no` (`coupon_no`) USING BTREE,
  KEY `idx_coupon_instance_template_id` (`template_id`) USING BTREE,
  KEY `idx_coupon_instance_user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠券';;

-- ============================================================
-- MOCK DATA (Demo only)
-- PKR / PKT (UTC+5). product_id=1 is assumed to exist in base configuration.
-- Integer state mapping used only by this demo seed:
-- application/disbursement/payment: 0 Pending, 1 Success/Approved, 2 Failed/Rejected, 3 Cancelled
-- voucher: 0 CoolingOff, 1 Active, 2 Overdue, 3 Paid, 4 WrittenOff
-- bill: 0 CoolingOff, 1 Active, 2 PartiallyPaid, 3 Overdue,
--       4 OverduePartiallyPaid, 5 Paid, 6 EarlySettled, 7 WrittenOff
-- user_id 9000001-9000020 are continuous mock identifiers. No user master table exists in this export.
-- Existing rows are preserved; excluded configuration tables are intentionally not written.
-- ============================================================

INSERT INTO `loan_credit_quota`
(`id`,`user_id`,`total_credit`,`used_credit`,`locked_credit`,`approved_time`,`is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<20)
SELECT 202608170100+i,9000000+i,8000+(i%5)*2000,
       CASE WHEN i IN (6,7,8,11,14,17,19,20) THEN 0
            WHEN i IN (3,5,12,18) THEN (4000+((i-1)%5)*1000)*0.75
            ELSE 4000+((i-1)%5)*1000 END,
       CASE WHEN i=19 THEN 3000 ELSE 0 END,
       DATE_ADD('2026-07-05 10:00:00',INTERVAL i DAY),0,'2026-07-01 09:00:00','2026-08-17 09:00:00'
FROM n;

INSERT INTO `loan_payment_account`
(`id`,`user_id`,`institution_code`,`identifier_enc`,`identifier_unique`,`state`,`is_snapshot`,`verification_time`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<20)
SELECT 202608170200+i,9000000+i,IF(i%2=0,'JAZZCASH','EASYPAISA'),
       CONCAT('mock_enc_',9000000+i),CONCAT('PK',9000000+i),IF(i=20,0,1),0,
       DATE_ADD('2026-07-06 11:00:00',INTERVAL i DAY),'2026-07-01 09:00:00','2026-08-17 09:00:00'
FROM n;

INSERT INTO `loan_apply_record`
(`id`,`apply_no`,`user_id`,`product_id`,`loan_amount`,`increase_limit_coupon_no`,`increase_limit_coupon_amount`,
 `term`,`period_days`,`total_days`,`daily_interest_rate`,`overdue_rate`,`total_interest`,`total_service_fee`,
 `total_repay_amount`,`rounding_waiver_amount`,`display_total_payable_amount`,`start_date`,`end_date`,`quick_review`,
 `state`,`pre_state`,`risk_state`,`term_infos`,`reject_reason`,`review_time`,`payment_account_id`,
 `disbursement_state`,`disbursement_time`,`disbursement_no`,`is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<24),
a AS (SELECT i,4000+((i-1)%5)*1000 amount FROM n)
SELECT 202608170300+i,CONCAT('APP202608',LPAD(i,4,'0')),9000000+((i-1)%20)+1,1,amount,'0',0,
       2,15,30,0.002000,0.010000,amount*0.06,amount*0.04,amount*1.10,0,amount*1.10,
       '2026-07-10','2026-08-09',IF(i%3=0,1,0),
       CASE WHEN i IN (19,24) THEN 0 WHEN i=22 THEN 2 WHEN i=23 THEN 3 ELSE 1 END,
       1,CASE WHEN i IN (19,23,24) THEN 0 WHEN i=22 THEN 2 ELSE 1 END,
       JSON_ARRAY(JSON_OBJECT('termSeq',1,'days',15),JSON_OBJECT('termSeq',2,'days',15)),
       CASE WHEN i=21 THEN 'Payment account verification failed' WHEN i=22 THEN 'Risk policy declined'
            WHEN i=23 THEN 'Cancelled by customer' ELSE NULL END,
       IF(i IN (19,23,24),NULL,DATE_ADD('2026-07-10 12:00:00',INTERVAL i HOUR)),
       202608170200+((i-1)%20)+1,
       CASE WHEN i IN (19,22,23,24) THEN NULL WHEN i=20 THEN 0 WHEN i=21 THEN 2 ELSE 1 END,
       IF(i<=18,DATE_ADD('2026-07-10 13:00:00',INTERVAL i HOUR),NULL),
       IF(i IN (19,22,23,24),NULL,CONCAT('DSB202608',LPAD(i,4,'0'))),0,
       DATE_ADD('2026-07-09 09:30:00',INTERVAL i HOUR),'2026-08-17 09:00:00'
FROM a;

INSERT INTO `loan_disbursement_record`
(`id`,`disbursement_no`,`apply_no`,`user_id`,`product_id`,`apply_amount`,`disbursed_amount`,`disbursement_channel`,
 `payment_account_id`,`channel_txn_no`,`state`,`fail_reason`,`request_time`,`success_time`,`callback_time`,`raw_payload`,
 `is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<21)
SELECT 202608170400+i,CONCAT('DSB202608',LPAD(i,4,'0')),CONCAT('APP202608',LPAD(i,4,'0')),
       9000000+((i-1)%20)+1,1,4000+((i-1)%5)*1000,
       IF(i<=18,4000+((i-1)%5)*1000,NULL),IF(i%2=0,'JazzCash','Easypaisa'),
       202608170200+((i-1)%20)+1,IF(i<=18,CONCAT('CH-DSB-',LPAD(i,4,'0')),NULL),
       CASE WHEN i<=18 THEN 1 WHEN i=20 THEN 0 ELSE 2 END,
       IF(i=21,'Payment account verification failed',NULL),
       DATE_ADD('2026-07-10 12:30:00',INTERVAL i HOUR),
       IF(i<=18,DATE_ADD('2026-07-10 13:00:00',INTERVAL i HOUR),NULL),
       IF(i<=18,DATE_ADD('2026-07-10 13:00:05',INTERVAL i HOUR),NULL),
       IF(i<=18,'{"mock":true,"result":"success"}','{"mock":true}'),0,
       '2026-07-10 12:30:00','2026-08-17 09:00:00'
FROM n
WHERE i<>19;

INSERT INTO `loan_voucher`
(`id`,`voucher_no`,`apply_no`,`disbursement_no`,`user_id`,`product_id`,`borrow_count`,`loan_amount`,`term`,`period_days`,
 `total_days`,`daily_interest_rate`,`overdue_rate`,`total_interest`,`total_service_fee`,`total_payable_amount`,`waiver_amount`,
 `display_payable_amount`,`start_date`,`end_date`,`cooling_off_start_time`,`cooling_off_end_time`,`fee_cap_amount`,`state`,
 `accumulated_fee_amount`,`total_overdue_fee`,`repay_coupon_amount`,`paid_principal`,`paid_interest`,`paid_service_fee`,
 `paid_overdue_fee`,`paid_amount`,`remaining_principal`,`remaining_interest`,`remaining_service_fee`,`remaining_overdue_fee`,
 `remaining_amount`,`payment_account_id`,`fee_capped`,`fee_capped_time`,`settled_type`,`settled_time`,`is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<18),
v AS (SELECT i,4000+((i-1)%5)*1000 amount,
 CASE WHEN i=1 THEN 0 WHEN i IN (4,5,10,13,16) THEN 2 WHEN i IN (6,7,11,14,17) THEN 3
      WHEN i=8 THEN 4 ELSE 1 END st FROM n),
x AS (SELECT *,IF(st=3,amount,IF(i IN (3,12,18),amount*0.25,IF(i=5,amount*0.25,0))) pp,
 IF(st=3,amount*0.06,IF(i IN (3,12,18,5),amount*0.015,0)) pi,
 IF(st=3,amount*0.04,IF(i IN (3,12,18),amount*0.01,0)) ps,
 IF(st=2,100+((i-1)%3)*50,IF(st=4,200,0)) od FROM v)
SELECT 202608170500+i,CONCAT('VCH202608',LPAD(i,4,'0')),CONCAT('APP202608',LPAD(i,4,'0')),
       CONCAT('DSB202608',LPAD(i,4,'0')),9000000+i,1,i-1,amount,2,15,30,0.002000,0.010000,
       amount*0.06,amount*0.04,amount*1.10,0,amount*1.10,'2026-07-10','2026-08-09',
       '2026-07-10 13:00:00','2026-07-11 13:00:00',amount,st,amount*0.10+od,od,0,
       pp,pi,ps,0,pp+pi+ps,amount-pp,amount*0.06-pi,amount*0.04-ps,od,
       amount-pp+amount*0.06-pi+amount*0.04-ps+od,202608170200+i,0,NULL,
       CASE WHEN st=3 AND i=7 THEN 'EARLY' WHEN st=3 THEN 'NORMAL' ELSE 'NONE' END,
       IF(st=3,'2026-08-10 16:00:00',NULL),0,'2026-07-10 13:00:00','2026-08-17 09:00:00'
FROM x;

INSERT INTO `loan_voucher_bill`
(`id`,`bill_no`,`voucher_no`,`user_id`,`product_id`,`term_seq`,`term`,`start_date`,`end_date`,`repay_date`,`period_days`,`state`,
 `payable_principal`,`payable_interest_amount`,`payable_service_fee`,`payable_overdue_fee`,`payable_amount`,`paid_principal`,
 `paid_interest`,`paid_service_fee`,`paid_overdue_fee`,`paid_amount`,`remaining_principal`,`remaining_interest`,
 `remaining_service_fee`,`remaining_overdue_fee`,`remaining_amount`,`overdue_days`,`is_overdue`,`settled_type`,`settled_time`,
 `settlement_record_no`,`settlement_bill_no`,`batching_time`,`is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<18),
t AS (SELECT 1 term_seq UNION ALL SELECT 2),
b AS (SELECT n.i,t.term_seq,4000+((n.i-1)%5)*1000 amount,
 CASE WHEN n.i=1 THEN 0 WHEN n.i IN (4,10,13,16) AND t.term_seq=1 THEN 3
      WHEN n.i=5 AND t.term_seq=1 THEN 4 WHEN n.i=8 THEN 7
      WHEN n.i IN (6,11,14,17) THEN 5 WHEN n.i=7 THEN 6
      WHEN n.i IN (3,12,18) AND t.term_seq=1 THEN 2 ELSE 1 END st FROM n CROSS JOIN t),
x AS (SELECT *,amount/2 p,amount*0.03 intr,amount*0.02 svc,
 IF(st IN (3,4),100+((i-1)%3)*50,IF(st=7,200,0)) od,
 IF(st IN (5,6),amount/2,IF(st IN (2,4),amount/4,0)) pp,
 IF(st IN (5,6),amount*0.03,IF(st IN (2,4),amount*0.015,0)) pi,
 IF(st IN (5,6),amount*0.02,IF(st=2,amount*0.01,0)) ps FROM b)
SELECT 202608171000+(i-1)*2+term_seq,CONCAT('BIL202608',LPAD(i,4,'0'),term_seq),
       CONCAT('VCH202608',LPAD(i,4,'0')),9000000+i,1,term_seq,2,
       IF(term_seq=1,'2026-07-10','2026-07-25'),IF(term_seq=1,'2026-07-24','2026-08-09'),
       IF(term_seq=1,'2026-07-24','2026-08-09'),15,st,p,intr,svc,od,p+intr+svc+od,
       pp,pi,ps,0,pp+pi+ps,p-pp,intr-pi,svc-ps,od,p+intr+svc+od-pp-pi-ps,
       IF(st IN (3,4,7),5+i,0),IF(st IN (3,4,7),1,0),
       CASE WHEN st=5 THEN 'NORMAL' WHEN st=6 THEN 'EARLY' ELSE 'NONE' END,
       IF(st IN (5,6),'2026-08-10 16:00:00',NULL),
       IF(st=6,CONCAT('ES202608',LPAD(i,4,'0')),NULL),IF(st=6,CONCAT('ESB202608',LPAD(i,4,'0')),NULL),
       '2026-08-17 00:05:00',0,'2026-07-10 13:01:00','2026-08-17 09:00:00'
FROM x;

INSERT INTO `loan_repayment_order`
(`id`,`repayment_no`,`voucher_no`,`user_id`,`product_id`,`channel_pay_no`,`payable_amount`,`difference_amount`,
 `coupon_no`,`coupon_amount`,`repay_start_time`,`repay_success_time`,`repay_type`,`repay_amount`,`pay_channel`,`pay_txn_no`,
 `wallet_type`,`wallet_real_name`,`wallet_account`,`pay_state`,`match_state`,`reconcile_state`,`fail_reason`,`reconciled_time`,
 `expire_time`,`is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<12)
SELECT 202608172000+i,CONCAT('RPY202608',LPAD(i,4,'0')),CONCAT('VCH202608',LPAD(i+1,4,'0')),
       9000001+i,1,IF(i IN (9,12),NULL,CONCAT('CP-',LPAD(i,4,'0'))),1500+(i%4)*500,
       IF(i IN (9,11,12),1500+(i%4)*500,0),NULL,0,DATE_ADD('2026-08-02 10:00:00',INTERVAL i DAY),
       IF(i IN (9,11,12),NULL,DATE_ADD('2026-08-02 10:02:00',INTERVAL i DAY)),
       IF(i%3=0,'PARTIAL','SCHEDULED'),IF(i IN (9,11,12),0,1500+(i%4)*500),
       IF(i%2=0,'JazzCash','Easypaisa'),IF(i IN (9,11,12),NULL,CONCAT('TXN-',LPAD(i,4,'0'))),
       IF(i%2=0,'JazzCash','Easypaisa'),CONCAT('Mock Payer ',i),CONCAT('0300***',1000+i),
       CASE WHEN i=11 THEN 0 WHEN i IN (9,12) THEN 2 ELSE 1 END,
       IF(i IN (9,11,12),0,1),IF(i IN (9,11,12),0,1),
       IF(i IN (9,12),'Insufficient wallet balance',NULL),IF(i IN (9,11,12),NULL,DATE_ADD('2026-08-02 11:00:00',INTERVAL i DAY)),
       DATE_ADD('2026-08-02 10:30:00',INTERVAL i DAY),0,DATE_ADD('2026-08-02 10:00:00',INTERVAL i DAY),'2026-08-17 09:00:00'
FROM n;

INSERT INTO `loan_repayment_bill`
(`id`,`voucher_no`,`bill_no`,`user_id`,`term_seq`,`state`,`original_bill_amount`,`bill_remaining_amount`,`coupon_amount`,
 `payable_amount`,`allocated_amount`,`difference_amount`,`paid_time`,`is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<12)
SELECT 202608173000+i,CONCAT('VCH202608',LPAD(i+1,4,'0')),CONCAT('BIL202608',LPAD(i+1,4,'0'),'1'),
       9000001+i,1,CASE WHEN i=11 THEN 0 WHEN i IN (9,12) THEN 2 ELSE 1 END,
       (4000+(i%5)*1000)*0.55,(4000+(i%5)*1000)*0.55,0,1500+(i%4)*500,
       IF(i IN (9,11,12),0,1500+(i%4)*500),IF(i IN (9,11,12),1500+(i%4)*500,0),
       IF(i IN (9,11,12),NULL,DATE_ADD('2026-08-02 10:02:00',INTERVAL i DAY)),0,
       DATE_ADD('2026-08-02 10:00:00',INTERVAL i DAY),'2026-08-17 09:00:00'
FROM n;

INSERT INTO `loan_repayment_allocation`
(`id`,`repayment_no`,`voucher_no`,`bill_no`,`user_id`,`product_id`,`term_seq`,`fee_type`,`allocated_amount`,
 `allocation_order`,`is_del`,`create_time`,`modify_time`)
WITH RECURSIVE n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<8),
f AS (SELECT 1 seq,'Interest' typ,300 amt UNION ALL SELECT 2,'ServiceFee',200 UNION ALL SELECT 3,'Principal',1500)
SELECT 202608174000+(i-1)*3+seq,CONCAT('RPY202608',LPAD(i,4,'0')),CONCAT('VCH202608',LPAD(i+1,4,'0')),
       CONCAT('BIL202608',LPAD(i+1,4,'0'),'1'),9000001+i,1,1,typ,amt,seq,0,
       DATE_ADD('2026-08-02 10:02:00',INTERVAL i DAY),'2026-08-17 09:00:00'
FROM n CROSS JOIN f;

INSERT INTO `loan_overdue_record`
(`id`,`overdue_no`,`voucher_no`,`bill_no`,`user_id`,`product_id`,`term_seq`,`overdue_date`,`overdue_days`,
 `overdue_rate`,`overdue_principal`,`overdue_base_amount`,`overdue_fee_amount`,`original_overdue_fee`,`posted_overdue_fee`,
 `posted_time`,`is_del`,`create_time`,`modify_time`)
WITH n AS (SELECT 4 i UNION ALL SELECT 5 UNION ALL SELECT 8 UNION ALL SELECT 10 UNION ALL SELECT 13 UNION ALL SELECT 16)
SELECT 202608175000+ROW_NUMBER() OVER(ORDER BY i),CONCAT('OD202608',LPAD(ROW_NUMBER() OVER(ORDER BY i),4,'0')),
       CONCAT('VCH202608',LPAD(i,4,'0')),CONCAT('BIL202608',LPAD(i,4,'0'),'1'),9000000+i,1,1,
       '2026-07-25',5+i,0.01,(4000+((i-1)%5)*1000)/2,(4000+((i-1)%5)*1000)/2,
       100+((i-1)%3)*50,100+((i-1)%3)*50,100+((i-1)%3)*50,'2026-08-17 00:05:00',0,
       '2026-07-25 00:05:00','2026-08-17 00:05:00'
FROM n;

INSERT INTO `loan_fee_adjust`
(`id`,`adjust_no`,`voucher_no`,`bill_no`,`user_id`,`product_id`,`fee_type`,`adjust_type`,`state`,`adjust_amount`,
 `before_amount`,`after_amount`,`reason`,`operator_id`,`reviewer_id`,`review_time`,`is_del`,`create_time`,`modify_time`) VALUES
(202608176001,'ADJ2026080001','VCH2026080004','BIL20260800041',9000004,1,'OverdueFee','Waive',0,50,150,100,'Customer hardship request',70001,NULL,NULL,0,'2026-08-16 09:00:00','2026-08-16 09:00:00'),
(202608176002,'ADJ2026080002','VCH2026080005','BIL20260800051',9000005,1,'OverdueFee','Waive',1,80,200,120,'Approved complaint resolution',70001,70002,'2026-08-16 14:00:00',0,'2026-08-16 09:30:00','2026-08-16 14:00:00'),
(202608176003,'ADJ2026080003','VCH2026080010','BIL20260800101',9000010,1,'ServiceFee','Decrease',2,30,100,100,'Evidence insufficient',70003,70002,'2026-08-16 15:00:00',0,'2026-08-16 10:00:00','2026-08-16 15:00:00');

INSERT INTO `loan_early_settlement_record`
(`id`,`settlement_no`,`voucher_no`,`user_id`,`product_id`,`settlement_date`,`original_remaining_contract_principal`,
 `original_remaining_overdue_fee`,`paid_normal_principal_amount`,`paid_normal_fee_interest`,`paid_normal_fee_service_fee`,
 `actual_used_days`,`actual_payable_interest`,`actual_payable_service_fee`,`settlement_payable_fee_amount`,`waived_interest`,
 `waived_service_fee`,`waived_overdue_fee`,`settlement_amount`,`repayment_no`,`status`,`paid_time`,`is_del`,`create_time`,`modify_time`) VALUES
(202608177001,'ES2026080007','VCH2026080007',9000007,1,'2026-08-10',5000,0,0,0,0,30,120,80,5200,0,0,0,5200,'RPY2026080006','Paid','2026-08-10 16:00:00',0,'2026-08-10 15:30:00','2026-08-10 16:00:00'),
(202608177002,'ES2026080012','VCH2026080012',9000012,1,'2026-08-17',3750,0,1250,75,50,38,150,100,4000,50,20,0,3930,NULL,'Pending',NULL,0,'2026-08-17 08:30:00','2026-08-17 08:30:00');

INSERT INTO `loan_bill_fee_changelog`
(`id`,`voucher_no`,`bill_no`,`user_id`,`product_id`,`term_seq`,`fee_type`,`change_type`,`source_type`,`source_no`,
 `change_amount`,`before_payable_amount`,`after_payable_amount`,`before_paid_amount`,`paid_change_amount`,`after_paid_amount`,
 `before_remaining_amount`,`after_remaining_amount`,`waived_change_amount`,`change_reason`,`operator_id`,`remark`,`is_del`,
 `create_time`,`modify_time`)
WITH n AS (SELECT 4 i UNION ALL SELECT 5 UNION ALL SELECT 8 UNION ALL SELECT 10 UNION ALL SELECT 13 UNION ALL SELECT 16)
SELECT 202608178000+ROW_NUMBER() OVER(ORDER BY i),CONCAT('VCH202608',LPAD(i,4,'0')),
       CONCAT('BIL202608',LPAD(i,4,'0'),'1'),9000000+i,1,1,'OverdueFee','Increase','Overdue',
       CONCAT('OD202608',LPAD(ROW_NUMBER() OVER(ORDER BY i),4,'0')),100+((i-1)%3)*50,0,100+((i-1)%3)*50,
       0,0,0,0,100+((i-1)%3)*50,0,'Daily overdue fee posting',NULL,'Demo batch posting',0,
       '2026-08-17 00:05:00','2026-08-17 00:05:00'
FROM n;

SET FOREIGN_KEY_CHECKS = 1;
